uint64 timestamp		# time since system start (microseconds)
float32 roll_correction		# roll correction
float32 pitch_correction	# pitch correction
float32 yaw_correction	        # yaw correction
float32 vx_correction	# vx correction
float32 vy_correction	# vy correction
float32 thrust_correction	# thrust correction
float32 nb_median		# number of median
float32 param_mr		# multiplier roll
float32 param_mp		# multiplier pitch
float32 param_my		# multiplier yaw
float32 param_mt		# mulitplier thrust
int32 median_roll		# median Roll
int32 median_pitch		# median Pitch
int32 median_yaw			# median Yaw
int32 median_vx		# median vx
int32 median_vy		# median vy
int32 median_thrust		# median Thrust

# TOPICS pipe_correction
