uint64 timestamp		# time since system start (microseconds)
float32 x_corr		# x correction
float32 y_corr		# y correction
float32 z_corr		# z correction
float32 vx_corr		# vx correction
float32 vy_corr		# vy correction
float32 vz_corr		# vz correction
float32 he_corr		# he correction
int32 median_x		# median x
int32 median_y		# median y
int32 median_z		# median z
int32 median_vx		# median vx
int32 median_vy		# median vy
int32 median_vz		# median vz
int32 median_he		# median he

# TOPICS pipepos_correction
